# Generated by Django 4.2.30 on 2026-05-29 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pastor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('church_name', models.CharField(blank=True, max_length=255, null=True)),
                ('social_twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('social_facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('social_youtube', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pastor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('AUDIO', 'Audio'), ('VIDEO', 'Vidéo'), ('BOTH', 'Les deux')], default='AUDIO', max_length=10)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('video_url', models.URLField(blank=True, help_text='Lien externe (YouTube, Vimeo, etc.)', null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('duration', models.IntegerField(default=0, help_text='Durée en secondes')),
                ('views_count', models.IntegerField(default=0)),
                ('downloads_count', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermons', to='api.pastor')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('PLAY_AUDIO', 'Lecture Audio'), ('WATCH_VIDEO', 'Lecture Vidéo'), ('DOWNLOAD', 'Téléchargement')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='api.sermon')),
            ],
        ),
    ]
