# Generated by Django 4.2.30 on 2026-05-29 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('est_masque', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='api.sermon')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Etiquette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.CharField(choices=[('ABUS', 'Abus'), ('DROITS', "Droits d'auteur"), ('HAINE', 'Discours haineux'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('EN_COURS', 'En cours'), ('TRAITE', 'Traite'), ('REJETE', 'Rejete')], default='NOUVEAU', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='api.commentaire')),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='api.sermon')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_couverture', models.ImageField(blank=True, null=True, upload_to='series/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pasteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='api.pastor')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('pasteur', 'titre')},
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='api.sermon')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='sermon',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='sermons', to='api.categorie'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='etiquettes',
            field=models.ManyToManyField(blank=True, related_name='sermons', to='api.etiquette'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons', to='api.serie'),
        ),
        migrations.CreateModel(
            name='HistoriqueLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_secondes', models.PositiveIntegerField(default=0)),
                ('est_termine', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques_lecture', to='api.sermon')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_lecture', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('utilisateur', 'sermon')},
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='api.sermon')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('utilisateur', 'sermon')},
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pasteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='api.pastor')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('utilisateur', 'pasteur')},
            },
        ),
    ]
