# Generated by Django 4.2.30 on 2026-05-29 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_categorie_commentaire_etiquette_signalement_serie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='cree_le'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='pasteur',
            field=models.ForeignKey(db_column='pasteur_id', on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='api.pastor'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='utilisateur',
            field=models.ForeignKey(db_column='utilisateur_id', on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analyticlog',
            name='action_type',
            field=models.CharField(choices=[('PLAY_AUDIO', 'Lecture Audio'), ('WATCH_VIDEO', 'Lecture Vidéo'), ('DOWNLOAD', 'Téléchargement')], db_column='type_action', max_length=20),
        ),
        migrations.AlterField(
            model_name='analyticlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_column='adresse_ip', null=True),
        ),
        migrations.AlterField(
            model_name='analyticlog',
            name='sermon',
            field=models.ForeignKey(db_column='predication_id', on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='api.sermon'),
        ),
        migrations.AlterField(
            model_name='analyticlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_column='cree_le'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='cree_le'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='description',
            field=models.TextField(blank=True, db_column='description', null=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(db_column='nom', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='contenu',
            field=models.TextField(db_column='contenu'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='cree_le'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='est_masque',
            field=models.BooleanField(db_column='est_masque', default=False),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='sermon',
            field=models.ForeignKey(db_column='predication_id', on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='api.sermon'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='modifie_le'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='utilisateur',
            field=models.ForeignKey(db_column='utilisateur_id', on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='etiquette',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='cree_le'),
        ),
        migrations.AlterField(
            model_name='etiquette',
            name='nom',
            field=models.CharField(db_column='nom', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='favori',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='cree_le'),
        ),
        migrations.AlterField(
            model_name='favori',
            name='sermon',
            field=models.ForeignKey(db_column='predication_id', on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='api.sermon'),
        ),
        migrations.AlterField(
            model_name='favori',
            name='utilisateur',
            field=models.ForeignKey(db_column='utilisateur_id', on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historiquelecture',
            name='est_termine',
            field=models.BooleanField(db_column='est_termine', default=False),
        ),
        migrations.AlterField(
            model_name='historiquelecture',
            name='position_secondes',
            field=models.PositiveIntegerField(db_column='position_secondes', default=0),
        ),
        migrations.AlterField(
            model_name='historiquelecture',
            name='sermon',
            field=models.ForeignKey(db_column='predication_id', on_delete=django.db.models.deletion.CASCADE, related_name='historiques_lecture', to='api.sermon'),
        ),
        migrations.AlterField(
            model_name='historiquelecture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='modifie_le'),
        ),
        migrations.AlterField(
            model_name='historiquelecture',
            name='utilisateur',
            field=models.ForeignKey(db_column='utilisateur_id', on_delete=django.db.models.deletion.CASCADE, related_name='historique_lecture', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pastor',
            name='avatar',
            field=models.ImageField(blank=True, db_column='avatar', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='pastor',
            name='bio',
            field=models.TextField(blank=True, db_column='biographie', null=True),
        ),
        migrations.AlterField(
            model_name='pastor',
            name='church_name',
            field=models.CharField(blank=True, db_column='nom_eglise', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pastor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='cree_le'),
        ),
        migrations.AlterField(
            model_name='pastor',
            name='display_name',
            field=models.CharField(db_column='nom_affichage', max_length=255),
        ),
        migrations.AlterField(
            model_name='pastor',
            name='social_facebook',
            field=models.CharField(blank=True, db_column='lien_facebook', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pastor',
            name='social_twitter',
            field=models.CharField(blank=True, db_column='lien_twitter', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pastor',
            name='social_youtube',
            field=models.CharField(blank=True, db_column='lien_youtube', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pastor',
            name='user',
            field=models.OneToOneField(db_column='utilisateur_id', on_delete=django.db.models.deletion.CASCADE, related_name='pastor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='piecejointe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='cree_le'),
        ),
        migrations.AlterField(
            model_name='piecejointe',
            name='fichier',
            field=models.FileField(db_column='fichier', upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='piecejointe',
            name='nom',
            field=models.CharField(db_column='nom', max_length=255),
        ),
        migrations.AlterField(
            model_name='piecejointe',
            name='sermon',
            field=models.ForeignKey(db_column='predication_id', on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='api.sermon'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='cree_le'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='description',
            field=models.TextField(blank=True, db_column='description', null=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='image_couverture',
            field=models.ImageField(blank=True, db_column='image_couverture', null=True, upload_to='series/'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='pasteur',
            field=models.ForeignKey(db_column='pasteur_id', on_delete=django.db.models.deletion.CASCADE, related_name='series', to='api.pastor'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='titre',
            field=models.CharField(db_column='titre', max_length=255),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='audio_file',
            field=models.FileField(blank=True, db_column='fichier_audio', null=True, upload_to='audios/'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='categories',
            field=models.ManyToManyField(blank=True, db_table='predications_categories', related_name='sermons', to='api.categorie'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='cover_image',
            field=models.ImageField(blank=True, db_column='image_couverture', null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='cree_le'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='description',
            field=models.TextField(blank=True, db_column='description', null=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='downloads_count',
            field=models.IntegerField(db_column='nombre_telechargements', default=0),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='duration',
            field=models.IntegerField(db_column='duree_secondes', default=0, help_text='Durée en secondes'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='etiquettes',
            field=models.ManyToManyField(blank=True, db_table='predications_etiquettes', related_name='sermons', to='api.etiquette'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='is_published',
            field=models.BooleanField(db_column='est_publie', default=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='media_type',
            field=models.CharField(choices=[('AUDIO', 'Audio'), ('VIDEO', 'Vidéo'), ('BOTH', 'Les deux')], db_column='type_media', default='AUDIO', max_length=10),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='pastor',
            field=models.ForeignKey(db_column='pasteur_id', on_delete=django.db.models.deletion.CASCADE, related_name='sermons', to='api.pastor'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='series',
            field=models.ForeignKey(blank=True, db_column='serie_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons', to='api.serie'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='title',
            field=models.CharField(db_column='titre', max_length=255),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='video_file',
            field=models.FileField(blank=True, db_column='fichier_video', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='video_url',
            field=models.URLField(blank=True, db_column='url_video', help_text='Lien externe (YouTube, Vimeo, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='views_count',
            field=models.IntegerField(db_column='nombre_vues', default=0),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='commentaire',
            field=models.ForeignKey(blank=True, db_column='commentaire_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='api.commentaire'),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='cree_le'),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='details',
            field=models.TextField(blank=True, db_column='details', null=True),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='raison',
            field=models.CharField(choices=[('ABUS', 'Abus'), ('DROITS', "Droits d'auteur"), ('HAINE', 'Discours haineux'), ('AUTRE', 'Autre')], db_column='raison', default='AUTRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='sermon',
            field=models.ForeignKey(db_column='predication_id', on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='api.sermon'),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='statut',
            field=models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('EN_COURS', 'En cours'), ('TRAITE', 'Traite'), ('REJETE', 'Rejete')], db_column='statut', default='NOUVEAU', max_length=20),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='utilisateur',
            field=models.ForeignKey(blank=True, db_column='utilisateur_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='abonnement',
            table='abonnements',
        ),
        migrations.AlterModelTable(
            name='analyticlog',
            table='journaux_analytiques',
        ),
        migrations.AlterModelTable(
            name='categorie',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='commentaire',
            table='commentaires',
        ),
        migrations.AlterModelTable(
            name='etiquette',
            table='etiquettes',
        ),
        migrations.AlterModelTable(
            name='favori',
            table='favoris',
        ),
        migrations.AlterModelTable(
            name='historiquelecture',
            table='historiques_lecture',
        ),
        migrations.AlterModelTable(
            name='pastor',
            table='pasteurs',
        ),
        migrations.AlterModelTable(
            name='piecejointe',
            table='pieces_jointes',
        ),
        migrations.AlterModelTable(
            name='serie',
            table='series',
        ),
        migrations.AlterModelTable(
            name='sermon',
            table='predications',
        ),
        migrations.AlterModelTable(
            name='signalement',
            table='signalements',
        ),
    ]
