# Generated by Django 4.2.30 on 2026-05-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_renommer_modeles_et_champs_en_francais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abonnement',
            options={'ordering': ['-cree_le']},
        ),
        migrations.AlterModelOptions(
            name='commentaire',
            options={'ordering': ['-cree_le']},
        ),
        migrations.AlterModelOptions(
            name='favori',
            options={'ordering': ['-cree_le']},
        ),
        migrations.AlterModelOptions(
            name='historiquelecture',
            options={'ordering': ['-modifie_le']},
        ),
        migrations.AlterModelOptions(
            name='serie',
            options={'ordering': ['-cree_le']},
        ),
        migrations.AlterModelOptions(
            name='signalement',
            options={'ordering': ['-cree_le']},
        ),
    ]
