# Generated by Django 4.2.30 on 2026-06-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_abonnement_options_alter_commentaire_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasteur',
            name='est_valide',
            field=models.BooleanField(db_column='est_valide', default=False, help_text='Indique si le compte du pasteur a été validé par un administrateur.'),
        ),
    ]
