# Generated by Django 4.2.30 on 2026-06-03 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_pasteur_est_valide'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verifie', models.BooleanField(db_column='email_verifie', default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_column='cree_le')),
                ('utilisateur', models.OneToOneField(db_column='utilisateur_id', on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profils_utilisateurs',
            },
        ),
    ]
