# Generated by Django 4.2.30 on 2026-06-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_profilutilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='predication',
            name='date_publication',
            field=models.DateTimeField(blank=True, db_column='date_publication', help_text="Si renseignee et future, la predication n'est publique qu'a partir de cette date.", null=True),
        ),
    ]
