# Generated by Django 4.2.30 on 2026-06-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_predication_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasteur',
            name='contact',
            field=models.CharField(blank=True, db_column='contact', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pasteur',
            name='logo_eglise',
            field=models.ImageField(blank=True, db_column='logo_eglise', null=True, upload_to='logos/'),
        ),
    ]
