# Generated by Django 4.2.30 on 2026-06-08 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_pasteur_contact_pasteur_logo_eglise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(db_column='message')),
                ('lu', models.BooleanField(db_column='lu', default=False)),
                ('type_notification', models.CharField(db_column='type_notification', default='ABONNEMENT', max_length=50)),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_column='cree_le')),
                ('utilisateur', models.ForeignKey(db_column='utilisateur_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_notification',
                'ordering': ['-cree_le'],
            },
        ),
    ]
