# Generated by Django 4.2.30 on 2026-06-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='predication',
            name='nom_predicateur',
            field=models.CharField(blank=True, db_column='nom_predicateur', help_text='Nom du prédicateur ou de la chaîne YouTube source, rempli automatiquement lors de la synchronisation.', max_length=255, null=True),
        ),
    ]
