# Generated by Django 4.2.30 on 2026-06-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_profilutilisateur_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandePasteur',
            fields=[
            ],
            options={
                'verbose_name': 'Demande de pasteur',
                'verbose_name_plural': 'Demandes de pasteurs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.pasteur',),
        ),
    ]
