# Generated by Django 4.2.30 on 2026-06-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_date_predication'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasteur',
            name='est_rejete',
            field=models.BooleanField(db_column='est_rejete', default=False, help_text='Indique si la demande du pasteur a été explicitement rejetée.'),
        ),
    ]
