# Generated by Django 4.2.30 on 2026-06-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_pasteur_est_rejete'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasteur',
            name='cree_par_admin',
            field=models.BooleanField(db_column='cree_par_admin', default=False, help_text='Indique si le compte a été créé par un administrateur.'),
        ),
    ]
