# Generated by Django 4.2.30 on 2026-06-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_pasteur_cree_par_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(db_column='titre', max_length=255)),
                ('message', models.TextField(db_column='message')),
                ('est_actif', models.BooleanField(db_column='est_actif', default=True, help_text="Indique si l'annonce doit être affichée sur la page d'accueil.")),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_column='cree_le')),
                ('date_expiration', models.DateTimeField(blank=True, db_column='date_expiration', help_text="Si renseignée, l'annonce expirera automatiquement à cette date.", null=True)),
            ],
            options={
                'db_table': 'annonces',
                'ordering': ['-cree_le'],
            },
        ),
    ]
