# Generated by Django 4.2.30 on 2026-06-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_annonce'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrouselMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, db_column='titre', max_length=255, null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('fichier', models.FileField(db_column='fichier', upload_to='carrousel/')),
                ('type_media', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Vidéo')], db_column='type_media', default='IMAGE', max_length=10)),
                ('est_actif', models.BooleanField(db_column='est_actif', default=True, help_text='Indique si le média doit être affiché dans le carrousel.')),
                ('ordre', models.IntegerField(db_column='ordre', default=0, help_text="Ordre d'affichage du média dans le carrousel.")),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_column='cree_le')),
            ],
            options={
                'db_table': 'carrousel_media',
                'ordering': ['ordre', '-cree_le'],
            },
        ),
    ]
