# Generated by Django 4.2.30 on 2026-06-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_carrouselmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrouselmedia',
            name='url_video',
            field=models.URLField(blank=True, db_column='url_video', help_text='Lien YouTube si le type est Vidéo.', null=True),
        ),
        migrations.AlterField(
            model_name='carrouselmedia',
            name='fichier',
            field=models.FileField(blank=True, db_column='fichier', help_text='Fichier image.', null=True, upload_to='carrousel/'),
        ),
        migrations.AlterField(
            model_name='carrouselmedia',
            name='ordre',
            field=models.IntegerField(db_column='ordre', default=0, help_text='Ordre daffichage du média dans le carrousel.'),
        ),
    ]
