# Generated by Django 4.2.30 on 2026-06-17 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_carrouselmedia_url_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(db_column='titre', max_length=255)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('fichier', models.FileField(db_column='fichier', upload_to='documents/')),
                ('image_couverture', models.ImageField(blank=True, db_column='image_couverture', null=True, upload_to='documents_covers/')),
                ('nombre_telechargements', models.IntegerField(db_column='nombre_telechargements', default=0)),
                ('est_publie', models.BooleanField(db_column='est_publie', default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_column='cree_le')),
                ('categories', models.ManyToManyField(blank=True, db_table='documents_categories', related_name='documents', to='api.categorie')),
                ('pasteur', models.ForeignKey(db_column='pasteur_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.pasteur')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-cree_le'],
            },
        ),
    ]
