# Generated by Django 4.2.30 on 2026-06-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_site', models.CharField(db_column='nom_site', default='Mon Eglise', max_length=255)),
                ('logo', models.ImageField(blank=True, db_column='logo', help_text='Logo global du site', null=True, upload_to='site/')),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True, db_column='mis_a_jour_le')),
            ],
            options={
                'verbose_name': 'Configuration du Site',
                'verbose_name_plural': 'Configuration du Site',
                'db_table': 'configuration_site',
            },
        ),
        migrations.AlterModelOptions(
            name='annonce',
            options={'ordering': ['-cree_le'], 'verbose_name': 'Annonce', 'verbose_name_plural': 'Annonces'},
        ),
        migrations.AlterModelOptions(
            name='carrouselmedia',
            options={'ordering': ['ordre', '-cree_le'], 'verbose_name': 'Média du Carrousel', 'verbose_name_plural': 'Médias du Carrousel'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-cree_le'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='piecejointe',
            options={'ordering': ['nom'], 'verbose_name': 'Pièce Jointe', 'verbose_name_plural': 'Pièces Jointes'},
        ),
    ]
