# Generated by Django 4.2.30 on 2026-06-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_configurationsite_alter_annonce_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predication',
            name='est_a_la_une',
            field=models.BooleanField(db_column='est_a_la_une', default=False, help_text='Afficher dans le carrousel À la une'),
        ),
    ]
