# Generated by Django 4.2.30 on 2026-07-12 16:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_predication_est_a_la_une'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTarifaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_column='nom', max_length=100)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('prix', models.DecimalField(db_column='prix', decimal_places=0, help_text='Prix en FCFA', max_digits=10)),
                ('duree_jours', models.IntegerField(db_column='duree_jours', default=30, help_text='Durée de validité en jours')),
                ('est_actif', models.BooleanField(db_column='est_actif', default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_column='cree_le')),
            ],
            options={
                'verbose_name': 'Plan Tarifaire',
                'verbose_name_plural': 'Plans Tarifaires',
                'db_table': 'plans_tarifaires',
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(db_column='montant', decimal_places=0, max_digits=10)),
                ('reference', models.CharField(db_column='reference', max_length=100, unique=True)),
                ('methode', models.CharField(choices=[('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('MTN_MONEY', 'MTN Mobile Money'), ('MOOV_MONEY', 'Moov Money')], db_column='methode', max_length=20)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Succès'), ('FAILED', 'Échoué')], db_column='statut', default='PENDING', max_length=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_column='cree_le')),
                ('maj_le', models.DateTimeField(auto_now=True, db_column='maj_le')),
                ('pasteur', models.ForeignKey(db_column='pasteur_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.pasteur')),
                ('plan', models.ForeignKey(db_column='plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.plantarifaire')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions_paiement',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='SouscriptionPasteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(db_column='date_debut', default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(db_column='date_fin')),
                ('est_essai', models.BooleanField(db_column='est_essai', default=False, help_text="Indique si c'est la période d'essai gratuite")),
                ('pasteur', models.OneToOneField(db_column='pasteur_id', on_delete=django.db.models.deletion.CASCADE, related_name='souscription', to='api.pasteur')),
                ('plan', models.ForeignKey(blank=True, db_column='plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.plantarifaire')),
            ],
            options={
                'verbose_name': 'Souscription Pasteur',
                'verbose_name_plural': 'Souscriptions Pasteurs',
                'db_table': 'souscriptions_pasteurs',
            },
        ),
    ]
