# Generated by Django 4.2.30 on 2026-08-27 08:42

import api.models.contenu
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_plans_tarifaires_par_defaut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predication',
            name='fichier_video',
            field=models.FileField(blank=True, db_column='fichier_video', null=True, upload_to=api.models.contenu.chemin_video_predication),
        ),
        migrations.CreateModel(
            name='TelechargementYoutube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ERREUR', 'Erreur')], db_column='statut', default='EN_COURS', max_length=10)),
                ('total_videos', models.IntegerField(db_column='total_videos', default=0)),
                ('videos_traitees', models.IntegerField(db_column='videos_traitees', default=0)),
                ('videos_echouees', models.IntegerField(db_column='videos_echouees', default=0)),
                ('message', models.TextField(blank=True, db_column='message', null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_column='cree_le')),
                ('termine_le', models.DateTimeField(blank=True, db_column='termine_le', null=True)),
                ('pasteur', models.ForeignKey(db_column='pasteur_id', on_delete=django.db.models.deletion.CASCADE, related_name='telechargements_youtube', to='api.pasteur')),
            ],
            options={
                'db_table': 'telechargements_youtube',
                'ordering': ['-cree_le'],
            },
        ),
    ]
