# Generated by Django 4.2.30 on 2026-08-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    """Le `upload_to` pointait a l'origine vers api.models.contenu.
    chemin_zip_telechargement, supprime avec la fonctionnalite de
    telechargement en masse. Remplace ici par un chemin litteral pour que
    cette migration historique reste rejouable sur une base neuve — le
    modele lui-meme est supprime par la migration 0030."""

    dependencies = [
        ('api', '0027_alter_predication_fichier_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telechargementyoutube',
            name='fichier_zip',
            field=models.FileField(blank=True, db_column='fichier_zip', null=True, upload_to='telechargements_youtube/'),
        ),
    ]
