# Generated by Django 4.2.30 on 2026-08-27 09:54

import api.models.contenu
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_predication_fichier_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telechargementyoutube',
            name='fichier_zip',
            field=models.FileField(blank=True, db_column='fichier_zip', null=True, upload_to=api.models.contenu.chemin_zip_telechargement),
        ),
    ]
