# Generated by Django 4.2.30 on 2026-08-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_telechargementyoutube_fichier_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='predication',
            name='date_predication',
            field=models.DateField(blank=True, db_column='date_predication', help_text='Date a laquelle la predication a ete donnee (distincte de la date de publication sur la plateforme).', null=True),
        ),
    ]
