# Generated by Django 4.2.30 on 2026-09-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_predication_date_predication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelechargementYoutube',
        ),
    ]
